from pathlib import Path
import uuid
import pandas as pd
from flask import Flask, jsonify, render_template, request, send_file
from werkzeug.utils import secure_filename

from analysis.analyzer import analyze_csv

BASE = Path(__file__).resolve().parent
UPLOAD = BASE / 'uploads'
UPLOAD.mkdir(exist_ok=True)

app = Flask(__name__)
app.config['MAX_CONTENT_LENGTH'] = 50 * 1024 * 1024
ALLOWED = {'csv'}
DERIVED_COLUMNS = {
    'Departure Year', 'Departure Month', 'Departure Month Name', 'Departure Day',
    'Day of Week', 'Day Type', 'Age Group', 'Travel Type (Approx.)'
}


def allowed(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED


def session_path(analysis_id):
    return UPLOAD / f'{analysis_id}_cleaned.csv'


def rebuild(analysis_id, filename):
    path = session_path(analysis_id)
    if not path.exists():
        raise FileNotFoundError('Analysis session not found.')
    return analyze_csv(path, path, filename, analysis_id)


@app.get('/')
def home():
    return render_template('index.html')


@app.post('/api/analyze')
def api_analyze():
    if 'file' not in request.files:
        return jsonify(error='Please select a CSV file.'), 400
    file = request.files['file']
    if not file.filename or not allowed(file.filename):
        return jsonify(error='Only CSV files are supported.'), 400

    analysis_id = uuid.uuid4().hex
    filename = secure_filename(file.filename)
    raw_path = UPLOAD / f'{analysis_id}_raw.csv'
    output_path = session_path(analysis_id)
    file.save(raw_path)
    try:
        result = analyze_csv(raw_path, output_path, filename, analysis_id)
        raw_path.unlink(missing_ok=True)
        return jsonify(result)
    except Exception as exc:
        raw_path.unlink(missing_ok=True)
        output_path.unlink(missing_ok=True)
        return jsonify(error='The dataset could not be analyzed.', details=str(exc)), 400


@app.post('/api/records/<analysis_id>')
def add_record(analysis_id):
    path = session_path(analysis_id)
    if not path.exists():
        return jsonify(error='Analysis session not found.'), 404
    payload = request.get_json(silent=True) or {}
    record = payload.get('record')
    if not isinstance(record, dict):
        return jsonify(error='A record object is required.'), 400
    try:
        df = pd.read_csv(path, low_memory=False)
        clean_record = {column: record.get(column, '') for column in df.columns if column not in DERIVED_COLUMNS}
        # Derived fields are intentionally regenerated by the analysis pipeline.
        for column in DERIVED_COLUMNS:
            if column in df.columns:
                clean_record[column] = ''
        df = pd.concat([pd.DataFrame([clean_record]), df], ignore_index=True)
        df.to_csv(path, index=False)
        return jsonify(rebuild(analysis_id, payload.get('filename', 'airline_dataset.csv')))
    except Exception as exc:
        return jsonify(error='Could not add the record.', details=str(exc)), 400


@app.put('/api/records/<analysis_id>/<int:index>')
def edit_record(analysis_id, index):
    path = session_path(analysis_id)
    if not path.exists():
        return jsonify(error='Analysis session not found.'), 404
    payload = request.get_json(silent=True) or {}
    record = payload.get('record')
    if not isinstance(record, dict):
        return jsonify(error='A record object is required.'), 400
    try:
        df = pd.read_csv(path, low_memory=False)
        if index < 0 or index >= len(df):
            return jsonify(error='Record index is out of range.'), 404
        for column in df.columns:
            if column in record and column not in DERIVED_COLUMNS:
                df.at[index, column] = record[column]
        df.to_csv(path, index=False)
        return jsonify(rebuild(analysis_id, payload.get('filename', 'airline_dataset.csv')))
    except Exception as exc:
        return jsonify(error='Could not edit the record.', details=str(exc)), 400


@app.delete('/api/records/<analysis_id>/<int:index>')
def delete_record(analysis_id, index):
    path = session_path(analysis_id)
    if not path.exists():
        return jsonify(error='Analysis session not found.'), 404
    try:
        df = pd.read_csv(path, low_memory=False)
        if index < 0 or index >= len(df):
            return jsonify(error='Record index is out of range.'), 404
        if len(df) <= 1:
            return jsonify(error='At least one record must remain.'), 400
        df = df.drop(index=index).reset_index(drop=True)
        df.to_csv(path, index=False)
        return jsonify(rebuild(analysis_id, request.args.get('filename', 'airline_dataset.csv')))
    except Exception as exc:
        return jsonify(error='Could not delete the record.', details=str(exc)), 400


@app.get('/api/download/<analysis_id>')
def download(analysis_id):
    path = session_path(analysis_id)
    if not path.exists():
        return jsonify(error='Cleaned dataset is no longer available.'), 404
    return send_file(path, as_attachment=True,
                     download_name='airline_cleaned_dataset.csv',
                     mimetype='text/csv')


@app.errorhandler(413)
def too_large(_):
    return jsonify(error='File is too large. Maximum size is 50 MB.'), 413


if __name__ == '__main__':
    app.run(debug=True)
